[formatter.nix]
command = "nixfmt"
includes = ["*.nix"]

[formatter.prettier]
command = "prettier"
options = ["--write"]
includes = ["*.css", "*.json", "*.jsonc", "*.md", "*.yaml", "*.yml"]
excludes = ["flake.lock", "assets/**"]

[formatter.lua]
command = "stylua"
includes = ["*.lua"]

[formatter.shell]
command = "shfmt"
options = ["-w", "-i", "2", "-ci"]
includes = ["*.sh"]
